name: CI/CD Lambda

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies and build package
        run: |
          pip install -r requirements.txt -t package/
          cp -r main.py controllers core registres repositories config clients services models package/
          cd package && zip -r ../function.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-package
          path: function.zip


  deploy:
    runs-on: ubuntu-latest
    needs: build   # 👈 depende de que build termine bien
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: lambda-package

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name ElJardinDeJane \
            --zip-file fileb://function.zip
